# Generated by Django 5.1.7 on 2025-03-30 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='mood_tags',
            field=models.CharField(blank=True, help_text='Comma-separated moods like happy, sadness, energetic', max_length=200),
        ),
    ]
