# Generated by Django 5.1.7 on 2025-03-30 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0002_song_mood_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='mood_tags',
        ),
        migrations.AddField(
            model_name='song',
            name='mood',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
