# Generated by Django 5.1.7 on 2025-03-30 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0003_remove_song_mood_tags_song_mood'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='mood',
        ),
        migrations.AddField(
            model_name='song',
            name='moods',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
